// Generated by CoffeeScript 1.6.3
(function() {
  define('os', ['localfile'], function(localfile) {
    var env, fs, system, ui;
    env = {};
    ui = {
      echo: console.log,
      ask: window.prompt
    };
    system = {
      db: function(msg, tag) {
        var tagRe, _i, _len, _ref, _ref1;
        if (tag == null) {
          return console.log(msg);
        }
        _ref1 = (_ref = db.tags) != null ? _ref : [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          tagRe = _ref1[_i];
          if (tagRe.test(tag)) {
            return console.log(msg);
          }
        }
      },
      exit: function(status) {
        throw 'OS exit with status: ' + status;
      }
    };
    system.db.tags = [/tag/];
    fs = {
      load: function(filepath) {
        return localfile.load(filepath);
      },
      save: function(filepath, content) {
        return localfile.save(filepath, content);
      },
      append: function(filepath, appendContent) {
        var content;
        if (content = this.load(filepath)) {
          content += appendConent + '\n';
          if (this.save(filepath, content)) {
            return content;
          }
        }
      }
    };
    return {
      env: env,
      fs: fs,
      ui: ui,
      system: system
    };
  });

}).call(this);
